apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

configMapGenerator:
  - name: config
    envs:
    - env.env
generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.cluster_name
    targets:
      - select:
          kind: EC2NodeClass
          name: default
        fieldPaths:
          - spec.subnetSelectorTerms.0.tags.name