name: Terraform Apply Dev

on:
  push:
    branches:
      - main
    paths:
      - 'workspaces/dev/**'

permissions:
  contents: read

jobs:
  terraform:
    name: 'RHEL Packer'
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: 1.1.0

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      run: "packer init rhel_prime.pkr.hcl"

    - name: Run Packer
      id: validate
      run: "packer build -var-file=Dev.pkrvars.json rhel_prime.pkr.hcl"
