---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-bar
  namespace: argocd
  finalizers:
    - resource-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/deepak-pradeep/argo-public.git
    targetRevision: HEAD
    path: apps/second-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolciy=foreground
      - PruneLast=true